[project]
name = "pepme"
version = "0.1.0"
description = "Metrics for benchmarking peptide generation models."
readme = "README.md"
authors = [
    { name = "Jan Olszewski", email = "janolszewski1906@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.9.4",
    "numpy>=2.0",
    "pandas>=2.0",
    "peptides>=0.3.4",
    "pydantic>=2.11.7",
    "pymoo>=0.6.1.5",
    "python-levenshtein>=0.27.1",
    "scipy>=1.13.1",
    "torch>=2.0",
    "tqdm>=4.67.1",
    "transformers>=4.53.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "nbstripout>=0.8.1",
    "pandas-stubs>=2.2.2.240807",
    "pre-commit-uv>=4.1.4",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
    "scipy-stubs>=1.15.3.0",
    "types-tqdm>=4.67.0.20250516",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.pydocstyle]
convention = "google"

