[project]
name = "pepme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Olszewski", email = "janolszewski1906@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.0",
    "pandas>=2.0",
    "torch>=2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "nbstripout>=0.8.1",
    "pre-commit-uv>=4.1.4",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
